services:
  - type: web
    name: learnlens
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: learnlens-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: learnlens-db
    plan: free