name: Python Application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      FLASK_APP: app.py
      FLASK_ENV: development
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --force-reinstall -U numpy==1.23.5
        pip install tensorflow==2.10.0
        pip install -r requirements.txt

    - name: Initialize database (optional)
      run: |
        flask init-db || echo "Skipping init-db (not defined)"

    - name: Run database migrations
      run: |
        flask db upgrade || echo "Skipping db upgrade (if Alembic not configured)"

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127

    - name: Build verification
      run: |
        python -c "from app import app; app.test_client().get('/')"
